### ISSUE TITLE
The real "value"

### ISSUE THREAD

**Issue by chaoxi24** [ordian/toml_edit#101]
hi. 
I want to know if there is a way to get the real value? "a"="s" -> a s
What we get now is  "a"="s" ->a "s"，we know that '""' is not part of the value.

**Comment by ordian** [comment]
hey, not sure exactly what you mean, but for values that are string you can use `as_str()` to remove the decoration part
https://docs.rs/toml_edit/0.2.0/toml_edit/enum.Value.html

**Comment by chaoxi24** [comment]
> 
> 
> hey, not sure exactly what you mean, but for values that are string you can use `as_str()` to remove the decoration part
> https://docs.rs/toml_edit/0.2.0/toml_edit/enum.Value.html

I'm very sorry, I didn't notice the "as_str()" method, I just used "to_string()".

**Comment by ordian** [comment]
No worries :) I hope that answered your question. The documentation is definitely needs to be improved and examples to be added.
I'll close the issue, but feel free to reopen if you disagree.
