### ISSUE TITLE
Table::get_mut?

### ISSUE THREAD

**Issue by anp** [ordian/toml_edit#105]
Thanks for the useful crate!

It looks like Table implements Index and IndexMut, and has an inherent method `Table::get` for getting an optional immutable reference, but there's no easy way to get an optional mutable reference to a key's value. I found myself writing code like this:

```rust
        if table.get(&key).is_some() {
            Some(&mut table[&key])
        } else {
            None
        }
```

It would be useful to expose a get_mut method too.

**Comment by ordian** [comment]
Hey, thanks!

We can expose `get_mut`, PRs are welcome! :-)

Note, with `IndexMut` API you can get an `Item::None` if the key is not found. So if you're looking for a `Value` (as in key/value pair), you can do `table[&key].as_value_mut()`.
