### ISSUE TITLE
as_table_like_ mut?

### ISSUE THREAD

**Issue by epage** [ordian/toml_edit#110]
I'm messing with Cargo.toml files and can't guarantee what fields will exist, so I use a lot of `get_mut`.  I also can't guarantee what style of table is being used, but there isn't a `as_table_like_mut`.

Any concerns with me adding this?

**Comment by ordian** [comment]
My main concern would be type-safety. I'd be possible to set a `Table` as a child of an `InlineTable`.
I just realized that #106 added `get_mut` to the `TableLike` trait. It slipped during review (and apart from that was technically a breaking change), but is useless right now.

**Comment by epage** [comment]
Ah, good point.   I'm trying to find every reference to a dependency and update its version.  I'll give some things a try.
