### ISSUE TITLE
Performance test against `toml-rs`

### ISSUE THREAD

**Issue by epage** [ordian/toml_edit#132]
The cargo team is concerned about negatively impacting `cargo`s performance in switching to `toml_edit`.  Specifically, they are concerned about parsing large dependency trees.

It is unclear how much impact `toml-rs` has on the whole operation and how much would be solved by
- Storing immutable `Cargo.toml` files in binary
- Moving strings in `cargo` to `smol_str` or `kstring`

But we should at least be able to say how we compare with the same API (#129)

- [x] #129 
- [x] Identify test cases to compare `toml_edit`, #129, and `toml-rs`
- [ ] Bring performance in line with `toml-rs`

**Comment by epage** [comment]
We take about twice as long, with the base API.  with the easy API, we take even longer.

Ideas
- Build up a table before inserting, rather than looking up the table on each key-value
- Dig through parser, looking for unneeded allocations
- `kstring` or something like it
- change our hash function

**Comment by epage** [comment]
My plan is to write up a bench for cargo to see how it performs in a more real-world use case and work with others on setting an acceptable performance target. I'll then look at holistic performance improvements, like using a String type in cargo and toml_edit with small-string optimization or caching parsed results for immutable Cargo.tomls (ie in the registry) in a more optimizable format, like json or cbor.

https://github.com/rust-lang/cargo/issues/9935 is relevant for the benchmark

**Comment by epage** [comment]
I've done small-string optimization for formatting and keys and various other improvements and brought parse time on a medium `Cargo.toml` from 250us to 200us.  

Potential next steps
- Switch parsers (I saw a lot of overhead from combine)
- Do small string optimization for values (hesitant to do this)

I guess I'm stuck with the above plan of moving from micro-benchmark to real-world resolver benchmarks.

**Comment by epage** [comment]
We've now dropped from the original 250us to 180us.  Still a good distance to the goal of 120us.

combine's `Errors::merge` is one of our biggest time sinks that seems "easy" to cut.  Easy because technically, we have no user-facing errors and we shouldn't need to call this at all.  However, what it takes to get `combine` to recognize that is another thing.

**Comment by epage** [comment]
Current breakdown for running my example, without printing
- 30% of time is spent in process startup (included since it skews the other percentages)
- 10% of time is spent copying strings (unaligned copies due to small-string optimization)
- 1.34% of time is spent in `std::str::from_utf8` (I was paranoid and didn't use `from_utf8_unchecked` in some places when switching to a byte parser, looks small enough to not be worth analyzing)
- 8% of time is malloc
- 1.5% of time is realloc
- 7.8% of time is spent in a `combine` call `Errors::merge` (which includes calling into malloc and realloc)

**Comment by epage** [comment]
Looks like the only options for dropping the `Errors::merge` overhead

From what I understand, this mostly comes from `choice` trying multiple parsers and returning their failures.  Once a parser "commits" (default behavior), it no longer does merging  If we use `attempt`, the parser doesn't commit.

- Replace `choice` with `dispatch`
  - This can really much up the grammar and break abstractions because the dispatch call needs to have knowledge of what the underlying parsers
  - This is a game of whack-a-mole
- Find ways to remove `attempt`
  - This is hard
  - This is a game of whack-a-mole
- Create a custom stream (rather than `combine::easy`) that still gives good errors but doesn't cost so much
  - Biggest risk but biggest potential pay off since its a fix once and it applies everywhere
- Switch to `nom` since it doesn't have these weird cases
  - This would also make profiling easier because costs would be associated with functions, rather than combinators returned by those functions
  - A decent amount of work (1-2 days)
  - A bit uglier because they rely on functions more (no `impl Parser` for tuples, much fewer functions on `Parser`)

**Comment by ordian** [comment]
Another option I considered is rewriting parser entirely using a recursive descent as done toml-rs. That's also a decent amount of work, but we'd gain more control this way in both error messages and overhead.

**Comment by epage** [comment]
Yes, its good to call that one out. I had originally dismissed it because I assume it'll be a significant amount of work to rewrite from scratch or even to figure out how to reuse parts of toml-rs with format-preserving.

**Comment by epage** [comment]
Also, one thing I've appreciated about `toml_edit` is its easy to map the code to the ABNF.  at least toml-rs doesn't maintain that.  Unsure how difficult it would be if we started completely from scratch

**Comment by epage** [comment]
Benchmarks came in around 5% slower.  Still acceptable for cargo
