### ISSUE TITLE
`easy::Value` equality doesn't handle keys being in other orders

### ISSUE THREAD

**Issue by epage** [ordian/toml_edit#194]
Noticed this when porting `toml-rs` tests.  `linked_hash_map` requires two maps to have keys in the same order to be equal.

Options
- `easy::Map` could have its own equality
- We can switch to `indexmap`, which is what `toml-rs` uses
  - It loses ordering on `remove` *but* I suspect that is less of a problem with us tracking table positions.   We don't track inline table positions (#163).

**Comment by ordian** [comment]
> It loses ordering on remove but I suspect that is less of a problem with us tracking table positions. We don't track inline table positions

If we only delete by replacing the value with `Item::None`, then it's even less of a problem. I was considering replacing `linked_hash_map` with `indexmap` as well esp. considering it's only in maintenance mode: https://github.com/contain-rs/linked-hash-map. I think we should do it.

**Comment by epage** [comment]
Good idea with the tombstones!

EDIT: Looks like they aren't needed, there is `shift_remove` that preserves order
