### ISSUE TITLE
Parse error on comment after datetime

### ISSUE THREAD

**Issue by ehuss** [ordian/toml_edit#269]
The following seems to fail to parse:

```toml
foo = 1979-05-27 # Comment
```

```
TOML parse error at line 2, column 18
  |
  2 | foo = 1979-05-27 # Comment
  |                  ^
  Unexpected `#`
expected 2 more elements
While parsing a Date-Time
```

But it works without the comment.

Currently using v0.10.0

**Comment by epage** [comment]
Thanks for reporting this! I'll try to get to this today, tomorrow at the latest.

**Comment by epage** [comment]
v0.10.1 is released with both fixes
