### ISSUE TITLE
Parse error on datetime with long fractional value

### ISSUE THREAD

**Issue by ehuss** [ordian/toml_edit#270]
The following seems to fail to parse:

```toml
bestdayever = 1987-07-05T17:45:00.123456789012345Z
```

```
TOML parse error at line 2, column 34
  |
  2 | bestdayever = 1987-07-05T17:45:00.123456789012345Z
  |                                  ^
  Unexpected `.`
Expected `#`
```

It works with just 9 digits.  This is part of the toml-rs testsuite.

I'm curious if there is some reason to have the limitation?  toml-rs will just truncate to the precision it allows.  If there is a good reason to reject it, I would expect the error message to be a little better. Though I think it is reasonable to just accept it with a small precision loss.

Using v0.10.0.

**Comment by epage** [comment]
Thanks for reporting this! I'll try to get to this today, tomorrow at the latest.

**Comment by ordian** [comment]
The [spec](https://toml.io/en/v1.0.0#offset-date-time) says:
> Millisecond precision is required. Further precision of fractional seconds is implementation-specific. If the value contains greater precision than the implementation can support, the additional precision must be truncated, not rounded.


so it sounds like a bug. We might consider option 1 from #188 (reverting #187).

**Comment by epage** [comment]
I'd be hesitant to add back in `chrono` for everyone.  Most people probably do not touch dates, adding an unused dependency.  Also it seems like there is uncertainty around `time` and `chrono` last I looked.
