### ISSUE TITLE
Docs reference to_string_in_original_order

### ISSUE THREAD

**Issue by webmaster128** [ordian/toml_edit#289]
In https://github.com/ordian/toml_edit/blob/a06c6f5a294155d39cdd06a586c6969027bdaea1/src/table.rs#L191-L197, the docs reference `Document::to_string_in_original_order` which seems to be gone.

I'm don't know how to best rewrite the text as I'm not sure if there are even two cases left or `set_position` is always respeced.

**Comment by epage** [comment]
Thanks for reporting this!  `set_position` is now always respected.  I've created a PR to fix this.
