### ISSUE TITLE
Insert at specific position

### ISSUE THREAD

**Issue by webmaster128** [ordian/toml_edit#291]
The `Table` positions are documented to only be set when they are parsed from a document. Is it possible in insert a table at a specific place of a document?

E.g. if I want to add a `[profile.custom]` before or after `[profile.release]` in https://github.com/CosmWasm/cosmwasm/blob/v1.0.0-beta4/contracts/hackatom/Cargo.toml#L13-L22, is that possible?

Right now I do

```rs
                let mut profile = toml_edit::Table::new();
                profile.set_implicit(true);
                profile.insert("custom", toml_edit::Item::Table(toml_edit::Table::new()));
                doc.insert("profile", toml_edit::Item::Table(profile));
```

which appends `[profile.custom]` at the end of the document.

**Comment by epage** [comment]
> The Table positions are documented to only be set when they are parsed from a document. Is it possible in insert a table at a specific place of a document?

Which piece of documentation are you referring to?  `set_position` exists to be able to control the ordering of **all** tables within a document.

**Comment by webmaster128** [comment]
Ah, cool. I guess it was a combination of

```rs
    // used for putting tables back in their original order when serialising.
    // Will be None when the Table wasn't parsed from a file.
    pub(crate) position: Option<usize>,
```

```rs
    /// Sets the position of the `Table` within the `Document`.
    ///
    /// Setting the position of a table will only affect output when
    /// `Document::to_string_in_original_order` is used.
    pub fn set_position(&mut self, position: usize) {
```

and 

```rs
    /// The position of the `Table` within the `Document`.
    ///
    /// Returns `None` if the `Table` was created manually (i.e. not via parsing)
    /// in which case its position is set automatically.
    pub fn position(&self) -> Option<usize> {
        self.position
    }
```

that made me think the position is exclusive to parsed elements.

But it seems to work with something like this 🚀

```rs
                let mut profile = toml_edit::Table::new();
                profile.set_implicit(true);
                profile.insert("release", toml_edit::Item::Table(toml_edit::Table::new()));
                profile.set_position(3);
                doc.insert("profile", toml_edit::Item::Table(profile));
```

If I insert a new Table into a document, do I have to manually adjust the positions of all elements later on?

**Comment by epage** [comment]
> If I insert a new Table into a document, do I have to manually adjust the positions of all elements later on?

Yes.  Something we could do to improve this is to sort by `(pos, path)` and not just `pos`.  This would allow people to reuse an existing tables position and get more predictable results.

**Comment by webmaster128** [comment]
I guess what confused me most is that the position information is stored in the child instead of the parent. I would have expected that in the `insert` method.

**Comment by epage** [comment]
> I guess what confused me most is that the position information is stored in the child instead of the parent. I would have expected that in the insert method.

Hopefully the explanation that the position is global helps clarify why its on the table and not on the parent.

It also can't be on `insert` because position handling of key-value pairs is different (local to the table its visually under, in the ideal case but its not fully implemented for dotted keys)

**Comment by epage** [comment]
As for the original request of this issue, because of the difference in how table vs key-value pair positioning works (not just how implemented), I'm inclined to close this out.

**Comment by webmaster128** [comment]
Thanks a lot for the help. Much appreciated.
