### ISSUE TITLE
Cannot serialize with string-like keys

### ISSUE THREAD

**Issue by jonhoo** [ordian/toml_edit#319]
The serialize logic for maps currently requires that keys either be `&str` (or `String`), _or_ be a newtype around such a type, as per

https://github.com/ordian/toml_edit/blob/bf5fb86a7e63f1a919dd507d98cbe082d6eb9614/src/ser/key.rs

any other type will generate an error with `ErrorKind::KeyNotString` kind saying "map key was not a string".

This makes it painful to have keys be "one of a known set", as expressed with a data-less enum, like so:

```rust
use serde::Serialize;
use std::collections::HashMap;

#[derive(Serialize, Hash, PartialEq, Eq)]
enum Foo {
    #[serde(rename = "hello")]
    Hello,
}

fn main() {
    let mut map = HashMap::new();
    map.insert(Foo::Hello, true);
    println!("{}", );
    println!("{}", toml_edit::ser::to_string(&map).unwrap());
}
```

Note that using `Foo` as a key works fine in maps with `serde_json` (`serde_json::to_string(&map).unwrap()`), whose key serialization logic lives here:

https://github.com/serde-rs/json/blob/2683b1aedc80e3b761033c13bd3359b56923253c/src/value/ser.rs#L441

The fix is to allow `serialize_unit_variant` to serialize using the variant name rather than generating `KeyNotString` here:

https://github.com/ordian/toml_edit/blob/bf5fb86a7e63f1a919dd507d98cbe082d6eb9614/src/ser/key.rs#L93-L100

serde_json allows that here:

https://github.com/serde-rs/json/blob/2683b1aedc80e3b761033c13bd3359b56923253c/src/value/ser.rs#L453-L461

**Comment by epage** [comment]
FYI this was carried over from `toml-rs`s serialization: https://github.com/alexcrichton/toml-rs/blob/master/src/ser.rs#L1448

Interesting that `serde_json` also serializes integers and chars but not bools or floats.

**Comment by jonhoo** [comment]
(PR coming soon btw)

**Comment by jonhoo** [comment]
PR with fix: https://github.com/ordian/toml_edit/pull/320

**Comment by epage** [comment]
v0.14.4 is now released with the fix
