### ISSUE TITLE
feature request: Deserialize from `Read` and Serialize into `Write`

### ISSUE THREAD

**Issue by NobodyXu** [ordian/toml_edit#326]
`toml_edit` currently requires the entire file to be read into `Vec<u8>` to deserialize and requires an intermediate `Vec<u8>` to serialize.

Having APIs for deserializing from `Read` and serialize directly into `Write` would avoid the intermediate buffer, provides better performance and less memory usage.

**Comment by epage** [comment]
So this isn't just supporting `Read` and `Write` but doing incremental parsing while doing using those traits.

Could you describe your use case where loading the toml into a buffer isn't sufficient?  Incremental parsing like that adds a lot of complexity and its hard to see the justification for it.

**Comment by NobodyXu** [comment]
@epage Not sure whether "incremental parsing" is the right word, but I just want something like [`serde_json::from_reader`](https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html) and [`serde_json::to_writer`](https://docs.rs/serde_json/latest/serde_json/fn.to_writer.html) where serializing/deserializing can be done without reading the entire file/writing the entire serialized content into `Vec<u8>`.

Looking at the implementation of `serde_json::Serialize`, this doesn't seem to be that hard and actually `serde` now recommends new format implementation to accept `Read` and `Write` and only provides a convenient function for reading from slice and writing to `Vec<u8>`.

**Comment by epage** [comment]
> this doesn't seem to be that hard

The parser has to be written with this use case in mind and can also potentially negatively impact performance to still get all of the desired feature (the error message with line/column information).  We have a very tight performance budget so we can be used in crates like cargo

**Comment by epage** [comment]
I'd also like to re-iterate my question

> Could you describe your use case where loading the toml into a buffer isn't sufficient? 

Generally TOML files are meant to be human edited which means their size is more constrained.  The use case for a TOML file where it is parsed a chunk at a time rather than loaded upfront seems relatively small.  We'd need to understand the use cases to determine if the benefits outweigh the costs.

**Comment by NobodyXu** [comment]
> Could you describe your use case where loading the toml into a buffer isn't sufficient?

I need to update `~/.cargo/.crates.toml` and I have no control on its size.

**Comment by epage** [comment]
While in theory that file can be unbounded, are you aware of any cases where it exceeds 1000 entries?

**Comment by NobodyXu** [comment]
> While in theory that file can be unbounded, are you aware of any cases where it exceeds 1000 entries?

No, at least not on my computer.

**Comment by epage** [comment]
Then the difference between using a `Read` and `Vec<u8>` is going to be negligible.

**Comment by NobodyXu** [comment]
Ok, I will close this issue then.

**Comment by tamird** [comment]
I have a use case where I'd like to emit TOML directly to a file. The previous discussion in this issue seems to have been focused on the **de**serialization challenges, but streaming serialization is quite straightforward (see #610).

Are there any objections to generalizing the serializer from `&mut String` to `impl std::fmt::Write`?

**Comment by epage** [comment]
Since you were aware of the issue, please move the conversation there.

**Comment by epage** [comment]
As I raised in #578, my main concern is that someone will see these "lower level" functions and assume they are more performant when they aren't.  

In the past, people have also brought up consistency with serde_json / following the recommendations at serde.rs.  To me, that motivation feels very weak.  Yes, this provides consistency but we aren't being consistent in their implementation.  For `serde_json`, they either are independent implementations or the higher-level ones (`from_string`) are implemented in terms of the lower level ones (`from_writer`).  For `toml`, we would be implementing the lower level ones (`from_writer`) in terms of the higher level (`from_string`).  So this becomes about expectation management.

For myself as well, I rarely interact with `File` but instead with `std::fs::read_string`.  The difference between the two is also negligible:
```rust
let data: MyStruct = serde_toml::from_reader(std::fs::File::open("sample.toml")?)?;
let data: MyStruct = serde_toml::from_string(std::fs::read_string("sample.toml")?)?;
```
If there was a significant benefit to `File` that might help tip the balance, but I don't really see that.

**Comment by tamird** [comment]
> As I raised in #578, my main concern is that someone will see these "lower level" functions and assume they are more performant when they aren't.

They may not be strictly more performant, but they will have different performance characteristics. In particular writing to a `File` directly will use less memory than first writing to a `String`. Using a `BufWriter` will provide a compromise between speed and memory usage.

> In the past, people have also brought up consistency with serde_json / following the recommendations at serde.rs. To me, that motivation feels very weak. Yes, this provides consistency but we aren't being consistent in their implementation. For `serde_json`, they either are independent implementations or the higher-level ones (`from_string`) are implemented in terms of the lower level ones (`from_writer`). For `toml`, we would be implementing the lower level ones (`from_writer`) in terms of the higher level (`from_string`). So this becomes about expectation management.

You seem to be talking about **de**serialization again (I assume you meant `from_reader`; `from_writer` doesn't make sense). I'm not looking to address **de**serialization.

> For myself as well, I rarely interact with `File` but instead with `std::fs::read_string`. The difference between the two is also negligible:
> 
> ```rust
> let data: MyStruct = serde_toml::from_reader(std::fs::File::open("sample.toml")?)?;
> let data: MyStruct = serde_toml::from_string(std::fs::read_string("sample.toml")?)?;
> ```

This seems to be focused on **de**serialization.

> If there was a significant benefit to `File` that might help tip the balance, but I don't really see that.

I've outlined the reasoning at the top of this comment; passing a `Writer` allows the caller to make performance/memory tradeoffs that are presently unavailable.

**Comment by epage** [comment]
> They may not be strictly more performant, but they will have different performance characteristics. In particular writing to a File directly will use less memory than first writing to a String. Using a BufWriter will provide a compromise between speed and memory usage.

I would like to see a benchmark to back up how much of a difference this makes within a real world application.  I expect it will not make enough of a difference to make up for what other misunderstandings people will have based on exposing this.

**Comment by tamird** [comment]
Can you help me understand what such a misunderstanding might be?

**Comment by epage** [comment]
Normally serde serializers immediately write to the writer as it gets each serde call. For the deserializers, they parse directly to serde calls. This offers the best performance. Bytes and string support is then built on top of this.

With `toml`, we deserialize a fully in-memory string into an AST and then into serde calls. For serialize, serde calls are used to generate a bare bones AST which we then clean up and then do a Write call to a string.

We can support all of the recommended API but the people will generally want that is for the performance benefits that are assumed with the implementation that we don't have. We could support dropping just the final string in serializations but it won't meet everyone's expectations and we wouldn't have symmetry.

**Comment by tamird** [comment]
> With `toml` [...] serialize, serde calls are used to generate a bare bones AST which we then clean up and then do a Write call to a string.

Are you suggesting that if the destination was a File rather than a string, there would be a single`write` syscall? My reading of the code suggests this is not the case. 

> We can support all of the recommended API but the people will generally want that is for the performance benefits that are assumed with the implementation that we don't have.

I don't understand. In my last comment I explained the performance tradeoffs that would become available to users if they could provide their own writer. You can in #610 that generalizing the writer is at once straightforward (almost entirely mechanical) and *pervasive* - that is, the change requires plumbing through all the serialization machinery. The latter point is telling: it strongly suggests that this *does not* amount to batching everything into a string and then making a single write call - rather we end up with a true streaming serializer.

> We could support dropping just the final string in serializations but it won't meet everyone's expectations and we wouldn't have symmetry.

It's true that there won't be symmetry between serialization and deserialization. Is that a problem?

**Comment by epage** [comment]
I was referring to the `write!` we do (which will translate to multiple `Write::write` calls in the end).

You mentioned theoretical performance improvements. I expect them to be minor compared to all the other work we are doing and in the bigger picture of your actually application. This is why I asked for numbers so that we can verify if it actually makes a difference.

**Comment by tamird** [comment]
Are there existing benchmarks I can use as a starting point? As I noted earlier, the change in #610 does not increase the complexity of the code; the need to justify it with proof of improvement (as opposed to proof of non-degradation) implies a status quo bias. I'd still be happy to enhance existing benchmarks to demonstrate the value.

**Comment by epage** [comment]
This is not a status quo bias but managing expectations and by providing this, we would be setting the wrong expectation.  I'm looking for proof that the we wouldn't be setting the wrong expectation.

Since you have an application you are wanting to use this in, would a benchmark of that application work?  All of our benchmarks are for other operations.

**Comment by NobodyXu** [comment]
I think it's possible to have a `deserialize_from_reader` API is hard to reuse and make sure people use buffered I/O:

```rust
fn deserialize_from_reader(reader: impl BufRead) -> ...
```

That would make sure the reader passed in buffered I/O input, either using `std::io::BufReader` or has some other custom implementation.

For serialization/write though, there's no such `BufWrite` trait in stdlib, so toml-edit could provide its own

```rust
/// Must be write buffered
trait BufWrite: std::io::Write {
}

impl<W: ?Sized + std::io::Write> BufWrite for std::io::BufWriter<W> {
}
```

It would prompt users to wrap the write in `std::io::BufWriter`, or they can implement it for their own type (or newtype) if they understand what they are doing and know that their writer already support buffering.

**Comment by tamird** [comment]
> This is not a status quo bias but managing expectations and by providing this, we would be setting the wrong expectation. I'm looking for proof that the we wouldn't be setting the wrong expectation.

What's the wrong expectation? Using a writer will do exactly what any API that uses a writer does.

> Since you have an application you are wanting to use this in, would a benchmark of that application work? All of our benchmarks are for other operations.

It's not exactly in a state I can contribute. I'll have to work up a benchmark, though I'm not sure how to benchmark memory use.

**Comment by epage** [comment]
I've explained the expectation issue in a couple of different ways now. Please go back and provide concrete questions to avoid us continuing in counter-productive loops.

**Comment by NobodyXu** [comment]
> With `toml`, we deserialize a fully in-memory string into an AST and then into serde calls. For serialize, serde calls are used to generate a bare bones AST which we then clean up and then do a Write call to a string.

Thanks for explanation, in that case it's indeed hard to provide the reader/writer API with the expected performance.
