### ISSUE TITLE
Missing a leading space on the value of a key-value pair?

### ISSUE THREAD

**Issue by pwoolcoc** [ordian/toml_edit#42]
I'm building a toml document through the API instead of the parser, and I'm wondering if I'm doing something wrong because I end up with key-value pairs that look like this: `key ="my value"` and `key =["my array"]`. From the looks of the `formatted.rs` code, there should be a space at the start of the value, but I'm not sure why it isn't working for me. Here is a minimal example:

```rust
extern crate toml_edit;
use toml_edit::{Array, Document, Item, Table, Value};

fn main() {
    let mut doc = Document::new();
    let mut root_table = Table::new();

    // items for the table
    let mut table = Table::new();
    let mut array = Array::default();
    array.push(Value::from("first-element"));
    *table.entry("my-key") = Item::Value(Value::from("my-value".to_string()));
    *table.entry("my-array") = Item::Value(Value::Array(array));

    *root_table.entry("my-table") = Item::Table(table);
    doc.root = Item::Table(root_table);
    println!("{}", doc);
}
```

and this is what I end up with:

```
[my-table]
my-key ="my-value"
my-array =["first-element"]
```

**Comment by ordian** [comment]
Hey @pwoolcoc,

In toml-edit each item carries around its formatting (incl. spaces around). When you create an item like `Item::Value(Value::from("my-value".to_string()))`, it has no spaces around.
The assign operator (`=`) assumes that the rhs is already formatted.

In the readme example, a formatted value is created using the `value` function, which does what you need.

I haven't tried this, but it should work:

```rust
extern crate toml_edit;
use toml_edit::{Array, Document, Item, Table, Value};

fn main() {
    let mut doc = Document::new();
    let mut root_table = Table::new();

    // items for the table
    let mut table = Table::new();
    let mut array = Array::default();
    array.push(Value::from("first-element"));
    table["my-key"] = value("my-value");
    table["my-array"] = value(array);

    root_table["my-table"] = Item::Table(table);
    doc.root = Item::Table(root_table);
    println!("{}", doc);
}
```

**Comment by pwoolcoc** [comment]
That works, thanks 👍 . The only issue is that `Array` doesn't implement `Into<Value>` so `value(array)` doesn't work, you have to do `value(Value::Array(array))`. I've opened a PR to add those `From` impls here: https://github.com/ordian/toml_edit/pull/43

**Comment by pwoolcoc** [comment]
Thanks!
