### ISSUE TITLE
reuse tokens from toml crate

### ISSUE THREAD

**Issue by ordian** [ordian/toml_edit#57]
cc https://github.com/rust-lang/cargo/pull/5611#issuecomment-420440837

**Comment by ordian** [comment]
Currently, `toml_edit`'s parser (https://github.com/ordian/toml_edit/tree/master/src/parser) operates on `&str`(https://github.com/ordian/toml_edit/blob/107868f14ec304e85d5545300fe74dc6a52c27df/src/parser/macros.rs#L9), but we would like to reuse the [token module from toml-rs](ttps://github.com/alexcrichton/toml-rs/blob/master/src/tokens.rs) by making it public (`pub mod tokens;` in lib.rs in toml-rs) and then rewriting our parser to operate on tokens instead of `&str` (see an example of combine-based parser on tokens [here](https://github.com/graphql-rust/graphql-parser/blob/master/src/tokenizer.rs))

**Comment by epage** [comment]
I think we can close this out at this point now that cargo has switched exclusively to toml_edit
