### ISSUE TITLE
add support for toml 1.0

### ISSUE THREAD

**Issue by ordian** [ordian/toml_edit#58]
- [ ] https://github.com/ordian/toml_edit/issues/128
- [x] https://github.com/ordian/toml_edit/issues/91
- [x] Verify encoding is compliant

**Comment by joseluis** [comment]
Toml 1.0 has finally been [released](https://github.com/toml-lang/toml/releases), and here is the updated spec (link in OP is dead):

https://github.com/toml-lang/toml/blob/master/toml.md

**Comment by ordian** [comment]
The spec is available here: https://toml.io/en/v1.0.0

One of the major changes is adding support for dotted keys. There is a WIP PR for that #73, but it hasn't been moving forward recently.

**Comment by epage** [comment]
Splitting out of https://github.com/rust-lang/cargo/issues/5586.

Just wanted to double check before you leave that you are good with continuing forward with updating the parser as-is or if the lexer re-work needs to be done and done first.  If so, I'll take up #73 and other conformance work for 1.0.

**Comment by ordian** [comment]
I think reworking the lexer (if there is a consensus it needs to be done) and comformance to 1.0 are two independent tasks.

**Comment by epage** [comment]
I'm going to declare us implementing 1.0 but with an open bug (#128)
