### ISSUE TITLE
toml_edit does not preserve table order

### ISSUE THREAD

**Issue by epage** [ordian/toml_edit#69]
As reported by @lucab  in https://github.com/sunng87/cargo-release/issues/144

Example of a diff where toml_edit re-ordered tables: https://github.com/coreos/afterburn/pull/269/files

Reproduction case using `cargo-script`

```rust
#!/usr/bin/env run-cargo-script
//! ```cargo
//! [dependencies]
//! toml_edit = "0.1"
//! difference = "2.0"
//! ```

fn main () {
    println!("Start");
    let original = r#"
[package]
name = "afterburn"
repository = "https://github.com/coreos/afterburn"
license = "Apache-2.0"
edition = "2018"
authors = [ "Stephen Demos <stephen.demos@coreos.com>",
            "Luca Bruno <lucab@debian.org>" ]
description = "A simple cloud provider agent"
version = "4.1.4-alpha.0"

[[bin]]
name = "afterburn"
path = "src/main.rs"

[profile.release]
lto = true

[dependencies]
base64 = "^0.10.1"
byteorder = "1.3"
clap = "2.33"
error-chain = { version = "0.12", default-features = false }
hostname = "0.1"
ipnetwork = "^0.14.0"
mime = "0.3"
nix = "^0.15.0"
openssh-keys = "^0.4.1"
openssl = "^0.10.24"
pnet_base = "^0.22.0"
pnet_datalink = "^0.22.0"
reqwest = "^0.9.19"
serde = "1.0"
serde-xml-rs = "0.3"
serde_derive = "1.0"
serde_json = "1.0"
slog-async = "2.1"
slog-scope = "~4.1"
slog-term = "2.4"
tempdir = "0.3"
tempfile = "^3.0.9"
update-ssh-keys = { version = "^0.5.0", optional = true }
users = "^0.9.1"

[features]
cl-legacy = ["update-ssh-keys"]

[dependencies.slog]
version = "2.5"
features = ["max_level_trace", "release_max_level_info"]

[dev-dependencies]
mockito = "^0.17.1"

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-push = true
disable-publish = true
pre-release-commit-message = "cargo: Afterburn release {{version}}"
pro-release-commit-message = "cargo: development version bump"
tag-message = "Afterburn v{{version}}"
tag-prefix = "v"

    "#;

    let manifest: toml_edit::Document = original.parse().unwrap();
    let new = manifest.to_string();
    difference::assert_diff!(&new, &original, "\n", 0);
}
```

**Comment by ordian** [comment]
@epage thanks for the report, this is a known limitation of `toml_edit`'s `.to_string()` that children tables are grouped after their parent, which is documented in the readme. We recently added file:///home/ordian/workspace/toml_edit/target/doc/toml_edit/struct.Document.html#method.to_string_in_original_order to support your use-case. Feel free to close the issue if you think it's resolved.

**Comment by epage** [comment]
Huh, somehow I missed that in the documentation when originally looking at the limitations.

If the goal is format preserving, should `to_string_in_original_order` be the default?  Seems less surprising that way (though probably requiring a "break in compat").

**Comment by ordian** [comment]
> If the goal is format preserving, should to_string_in_original_order be the default? Seems less surprising that way (though probably requiring a "break in compat").

Yes, the main concern here was the compatibility. Also there are some edge cases with `to_string_in_original_order` if you do swapping of tables from different documents, the output could be unexpected. So there is a general trade-off between type-safe API with tree-like layout and fully preserving order.
