### ISSUE TITLE
[feature] Table -> InlineTable

### ISSUE THREAD

**Issue by gabbifish** [ordian/toml_edit#74]
Hello! I'm trying to turn 
```toml
[site]
bucket = ""
entry-point = "workers-site"
```
into an inline table using toml_edit. Oddly enough, when I parse my toml, I get
```
Table(Table { items: {"bucket": TableKeyValue { key: Repr { decor: Decor { prefix: "", suffix: " " }, raw_value: "bucket" }, value: Value(String(Formatted { value: "", repr: Repr { decor: Decor { prefix: " ", suffix: "" }, raw_value: "\"\"" } })) }, "entry-point": TableKeyValue { key: Repr { decor: Decor { prefix: "", suffix: " " }, raw_value: "entry-point" }, value: Value(String(Formatted { value: "workers-site", repr: Repr { decor: Decor { prefix: " ", suffix: "" }, raw_value: "\"workers-site\"" } })) }}, decor: Decor { prefix: "\n", suffix: "" }, implicit: false, position: Some(1) })
```
Type `Table(Table...` was not I expected to see above, and I suspect it's why calling `.as_inline_table()` fails on the table provided above. (instead, calling `.as_inline_table()` returns `None`).

Any pieces of advice? :)

**Comment by ordian** [comment]
hey @gabbifish! This is the expected output. Inline tables are something different: https://github.com/toml-lang/toml#user-content-inline-table.
For example,
```toml
site = { bucket = "", entry-point = "workers-site" }
```
This would be an equivalent inline table in your case. Does that make sense?

**Comment by ordian** [comment]
Ah, I see you're trying to convert a `Table` into an `InlineTable` and expecting `as_inline_table` to do the conversion. But that's not what it does. It performs a dynamic check and returns `Some(InlineTable)` if it's actually is an InlineTable.
Currently, the functionality you asking is missing: https://github.com/ordian/toml_edit/blob/b679b5e610b9a19f48fa0268f9174062e9c43962/src/table.rs#L8

PRs are welcome :)

**Comment by pshirshov** [comment]
Here is my snippet which converts `Table` into `InlineTable`:

```rust
fn make_inline_tbls(paths_arr: &mut ArrayOfTables) {
    for x in (0..paths_arr.len()) {
        let sub = paths_arr.get_mut(x).expect("");
        let tgt_raw = sub.entry("target");

        tgt_raw.as_inline_table_mut().map(|e| e.fmt());
        let tgt_table = tgt_raw.as_table().expect("");
        let mut tgt_inline = InlineTable::default();
        tgt_table.iter().for_each(|i| {
            let key = i.0;
            let value = i.1.as_value().expect("").to_owned();
            tgt_inline.get_or_insert(key, value);
        });
        tgt_inline.fmt();


        let mut tgt_val = Value::InlineTable(tgt_inline);
        let tgt_item = Item::Value(tgt_val);
        *tgt_raw = tgt_item;

    }
}
```

I'm not a rustacean, so, probably, this is a piece of crap, though it works. Would really like to see a built-in API.

**Comment by epage** [comment]
The next release includes a `item.into_value()` which will turn a table into an inline table.  We don't have an in-place version yet, so you'll have to remove, convert, and insert.
